### ISSUE TITLE
minSDK版本最低21没有必要

### ISSUE THREAD

**Issue by eleveno** [hi-dhl/Binding#1]
引用到项目中时提示最低SDK要求是21，但是其实没有必要这个限制，可以改低一点

**Comment by hi-dhl** [comment]
@eleveno  好的，正在加入其他功能，同时会将版本降低

**Comment by hi-dhl** [comment]
* 最低 SDK 降低至 14， 可以添加依赖 `implementation 'com.hi-dhl:binding:1.0.3` ，
* 1.0.3 增加了新的功能可以查看 README.md

感谢支持！！
