### ISSUE TITLE
请问如何迁移呢

### ISSUE THREAD

**Issue by mcxinyu** [hi-dhl/Binding#10]
请问项目从butterknife或者fvb，如何迁移过来呢？好像viewbinding一打开，所以xml就被解析了。

**Comment by hi-dhl** [comment]
@mcxinyu 是的，只要开启 `viewBinding = true` 就会解析，但是可以将下面属性添加到布局文件的根视图中, 就不会生成 binding 类了

```
<LinearLayout tools:viewBindingIgnore="true" >
</LinearLayout>
```

如果之前使用 butterknife 和 findViewById 部分视图，可以添加上述属性，避免生成不需要的类。

butterknife 和 findViewById 这个可以不需要动，只需要迁移 Kotlin 合成方法（Synthetic 视图） 即可，因为 Google 可能会在今年 9月份之后，移除掉 `kotlin-android-extensions` 插件

从目前来说迁移 Synthetic 视图 ，如果数量少的话可以手动迁移，如果数量大的话，暂时不需要动，等待后面根据实际情况做相应的调整

但是新的功能建议使用 viewbinding，不要在使用旧的方式了

**Comment by mcxinyu** [comment]
对，就是这个问题，我需要给 1000+ 个 layout 文件都添加 tools:viewBindingIgnore="true"，这样操作很难受，可能要写个程序来执行了，或者就是你说的暂时不要动了。

但是 as 有时候会出问题，告警“资源 id 已经不是 final 类型啦...”，然后经常增删改某个 id，在运行程序的时候就会奔溃（第一次没有增删改这个 id ），需要重试一次。

**Comment by hi-dhl** [comment]
* 如果 layout 文件很多就不需要动了，这个成本还挺大的
* 为什么会出现经常 “增删改某个 id 情况” 呢，这个应该不会经常变才对，可能偶尔会改 1、2次， 我感觉应该没有使用 AS 的快捷键去重命名，如果使用快捷键，应该不会出现问题。
* 如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改

**Comment by df13954** [comment]
> * 如果 layout 文件很多就不需要动了，这个成本还挺大的
> * 为什么会出现经常 “增删改某个 id 情况” 呢，这个应该不会经常变才对，可能偶尔会改 1、2次， 我感觉应该没有使用 AS 的快捷键去重命名，如果使用快捷键，应该不会出现问题。
> * 如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改

【如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改】这很不友好，最近as新版本各种小问题很恶心人，公司的项目一直不敢用最新的开发，目前发现401很稳定。
用了一周的时间，把butter，和kext的代码全部换了原生的，换完发现，你这个库。太及时了

**Comment by hi-dhl** [comment]
> > * 如果 layout 文件很多就不需要动了，这个成本还挺大的
> > * 为什么会出现经常 “增删改某个 id 情况” 呢，这个应该不会经常变才对，可能偶尔会改 1、2次， 我感觉应该没有使用 AS 的快捷键去重命名，如果使用快捷键，应该不会出现问题。
> > * 如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改
> 
> 【如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改】这很不友好，最近as新版本各种小问题很恶心人，公司的项目一直不敢用最新的开发，目前发现401很稳定。
> 用了一周的时间，把butter，和kext的代码全部换了原生的，换完发现，你这个库。太及时了

赞，替换的工作量相当大

**Comment by hi-dhl** [comment]
> 对，就是这个问题，我需要给 1000+ 个 layout 文件都添加 tools:viewBindingIgnore="true"，这样操作很难受，可能要写个程序来执行了，或者就是你说的暂时不要动了。
> 
> 但是 as 有时候会出问题，告警“资源 id 已经不是 final 类型啦...”，然后经常增删改某个 id，在运行程序的时候就会奔溃（第一次没有增删改这个 id ），需要重试一次。

在 layout 文件都添加 tools:viewBindingIgnore="true" ，可以通过 AS 快捷键，一键将之前的XML 文件全部替换

**Comment by df13954** [comment]
> > > * 如果 layout 文件很多就不需要动了，这个成本还挺大的
> > > * 为什么会出现经常 “增删改某个 id 情况” 呢，这个应该不会经常变才对，可能偶尔会改 1、2次， 我感觉应该没有使用 AS 的快捷键去重命名，如果使用快捷键，应该不会出现问题。
> > > * 如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改
> > 
> > 
> > 【如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改】这很不友好，最近as新版本各种小问题很恶心人，公司的项目一直不敢用最新的开发，目前发现401很稳定。
> > 用了一周的时间，把butter，和kext的代码全部换了原生的，换完发现，你这个库。太及时了
> 
> 赞，替换的工作量相当大

我把旧模块换原生，不管他以后怎么搞，总不会原生出问题吧，这也是无奈啊，kext不能继续用，butter也是。
现在不改，以后更加没时间，还不如先痛

**Comment by hi-dhl** [comment]
> > > > * 如果 layout 文件很多就不需要动了，这个成本还挺大的
> > > > * 为什么会出现经常 “增删改某个 id 情况” 呢，这个应该不会经常变才对，可能偶尔会改 1、2次， 我感觉应该没有使用 AS 的快捷键去重命名，如果使用快捷键，应该不会出现问题。
> > > > * 如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改
> > > 
> > > 
> > > 【如果使用 viewBinding 的话，目前版本的 AS 支持不完善，使用快捷键去修改 id，代码内引用的 id 还是需要手动修改】这很不友好，最近as新版本各种小问题很恶心人，公司的项目一直不敢用最新的开发，目前发现401很稳定。
> > > 用了一周的时间，把butter，和kext的代码全部换了原生的，换完发现，你这个库。太及时了
> > 
> > 
> > 赞，替换的工作量相当大
> 
> 我把旧模块换原生，不管他以后怎么搞，总不会原生出问题吧，这也是无奈啊，kext不能继续用，butter也是。
> 现在不改，以后更加没时间，还不如先痛

嗯嗯，对，最终都脱离不了原生的，我们现在在新功能都开始使用 Binding 了，禁用了 kotlin 合成的语法了

**Comment by mcxinyu** [comment]
@hi-dhl 不好操作，有的文件还要多添加一行tools命名空间，这样就不好判断了。自己写个java代码解析下xml算了，还是有其他方法？

**Comment by hi-dhl** [comment]
> @hi-dhl 不好操作，有的文件还要多添加一行tools命名空间，这样就不好判断了。自己写个java代码解析下xml算了，还是有其他方法？

我在解释一下刚才的方式：

因为基本每个XML 文件都会包含 `xmlns:android="http://schemas.android.com/apk/res/android"`

1. 可以使用快捷键 搜索 `xmlns:android="http://schemas.android.com/apk/res/android"` 
2. 然后替换为`xxmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools  "
tools:viewBindingIgnore="true"`

最后使用 spotless 将xml 资源文件格式化一下就好了，你可以先试一下使用快捷键替换 2 个xml 文件试一下

**Comment by mcxinyu** [comment]
@hi-dhl 我之前也这样做过，后来放弃了，因为有些xml文件已经有 
```
xmlns:tools="http://schemas.android.com/tools"
```
了，数量还不少，重复会报错。

**Comment by mcxinyu** [comment]
感觉 google 应该推个像 merge to AndroidX 一样的工具来解决存量代码的问题。

**Comment by df13954** [comment]
> 感觉 google 应该推个像 merge to AndroidX 一样的工具来解决存量代码的问题。

可试试这种方式https://blog.csdn.net/weixin_43269414/article/details/107839575

**Comment by hi-dhl** [comment]
> @hi-dhl 我之前也这样做过，后来放弃了，因为有些xml文件已经有
> 
> ```
> xmlns:tools="http://schemas.android.com/tools"
> ```
> 
> 了，数量还不少，重复会报错。

拆分步骤 如果包含 xmlns:tools 的只增加 tools:viewBindingIgnore="true" 即可，其余的按照上面说的方式处理，可以指定文件夹进行替换，多多少少会出现问题，但是出现问题，编译就会出错，手动改一下就好

如果项目评估 APK 体积增加一点，影响不是很大，之前的方式可以不做处理

**Comment by mcxinyu** [comment]
@hi-dhl 可以吧，先把所有tools的命名空间替换为空字符串，再走你这里的替换方法。

**Comment by mcxinyu** [comment]
@ff-frida 好的，其实idea或者说Android studio已经有这种功能了。

**Comment by df13954** [comment]
> @ff-frida 好的，其实idea或者说Android studio已经有这种功能了。

不好意思，这个功能真没发现，可以告知怎么操作吗

**Comment by mcxinyu** [comment]
> > @ff-frida 好的，其实idea或者说Android studio已经有这种功能了。
> 
> 不好意思，这个功能真没发现，可以告知怎么操作吗
请看

![image](https://user-images.githubusercontent.com/9566116/104692995-df8e4380-5743-11eb-8ff6-0cef6032486d.png)
快捷键 ctrl+shift+R，操作如下图，比 Notepad 多一个功能就是**显示即将要替换的位置和所在文件**，而且更强大的是“**这里还可以编辑**”，这样不想替换的就可以直接点下一个**跳过**，而且还可以跟其他功能再搭配使用。

![image](https://user-images.githubusercontent.com/9566116/104693333-6ba06b00-5744-11eb-8062-d4ecae0a31f7.png)

**Comment by df13954** [comment]
> > > @ff-frida 好的，其实idea或者说Android studio已经有这种功能了。
> > 
> > 
> > 不好意思，这个功能真没发现，可以告知怎么操作吗
> > 请看
> 
> ![image](https://user-images.githubusercontent.com/9566116/104692995-df8e4380-5743-11eb-8ff6-0cef6032486d.png)
> 快捷键 ctrl+shift+R，操作如下图，比 Notepad 多一个功能就是**显示即将要替换的位置和所在文件**，而且更强大的是“**这里还可以编辑**”，这样不想替换的就可以直接点下一个**跳过**，而且还可以跟其他功能再搭配使用。
> 
> ![image](https://user-images.githubusercontent.com/9566116/104693333-6ba06b00-5744-11eb-8062-d4ecae0a31f7.png)

3q
