### ISSUE TITLE
和JDataBinding一起用冲突吗

### ISSUE THREAD

**Issue by ljackChen001** [hi-dhl/Binding#14]

**Comment by hi-dhl** [comment]
不冲突，可以一起使用，ViewBinding 和 DataBinding 使用 binding 库即可， adapter 使用 JDataBinding，后期会将 JDataBinding 里面的 adapter  和 binding 分离开来

**Comment by hi-dhl** [comment]
同时也会对 Paging3 中的 adapter 做支持

**Comment by hi-dhl** [comment]
非常感谢你的提交，我将要关闭这个 issue，欢迎你再次提 issue
