### ISSUE TITLE
在dialog中使用，然后绑定自定义View的自定义事件，该自定义事件为空

### ISSUE THREAD

**Issue by shenyunhuan** [hi-dhl/Binding#19]
用viewBinding模式，在dialog中使用，然后绑定自定义View的自定义事件，该自定义事件为空，使用contentView.id的形式就正常了

**Comment by shenyunhuan** [comment]
class ScreenDialog(context: Context) : Dialog(context, R.style.CommentDialog) {

//    private val binding:DialogScreenBinding by viewbind()
    fun initUI(action: (Int) -> Unit): ScreenDialog {
        window?.setGravity(Gravity.BOTTOM)
        val contentView = layoutInflater.inflate(R.layout.dialog_screen, null, false);

    contentView.iv_dialog_cancel.click {
            dismiss()
        }
//    binding.rangeSeekBar.listenerPost = 这样不正常
        contentView.range_seek_bar.listenerPost = object :RangeSeekBar.OnRangeSeekBarPostListener {
            override fun onValuesChanged(minValue: Float, maxValue: Float) {
                ToastUtil.instance.show(context,messageStr = "$minValue $maxValue")
            }

            override fun onValuesChanged(min: Int, max: Int) {
                ToastUtil.instance.show(context,messageStr = "$min $max")
            }
        }
//        range_slider.apply {
//        }
        addContentView(
            contentView,
            ViewGroup.LayoutParams(context.screenWidth - 40, ViewGroup.LayoutParams.WRAP_CONTENT)
        )
        return this
    }



}

**Comment by hi-dhl** [comment]
非常感谢你的反馈，

我在 demo 中增加了 Dialog 绑定系统的 Listener 和 自定义View 的 Listener， 测试一下是正常的，如果我的代码 和你的 “自定义View的自定义事件” 有出入，烦请告诉我，我在尝试一下，代码如下所示：

https://github.com/hi-dhl/Binding/blob/f21547a27ddeaffcab474cc2a12a3d9c1eebb647/app/src/main/java/com/hi/dhl/demo/binding/viewbind/ViewBindDialog.kt#L29-L36

自定义事件为空，看一下是否初始化了 自定义事件

**Comment by hi-dhl** [comment]
> class ScreenDialog(context: Context) : Dialog(context, R.style.CommentDialog) {
> 
> // private val binding:DialogScreenBinding by viewbind()
> fun initUI(action: (Int) -> Unit): ScreenDialog {
> window?.setGravity(Gravity.BOTTOM)
> val contentView = layoutInflater.inflate(R.layout.dialog_screen, null, false);
> 
> ```
> contentView.iv_dialog_cancel.click {
>         dismiss()
>     }
> ```
> 
> // binding.rangeSeekBar.listenerPost = 这样不正常
> contentView.range_seek_bar.listenerPost = object :RangeSeekBar.OnRangeSeekBarPostListener {
> override fun onValuesChanged(minValue: Float, maxValue: Float) {
> ToastUtil.instance.show(context,messageStr = "$minValue $maxValue")
> }
> 
> ```
>         override fun onValuesChanged(min: Int, max: Int) {
>             ToastUtil.instance.show(context,messageStr = "$min $max")
>         }
>     }
> ```
> 
> // range_slider.apply {
> // }
> addContentView(
> contentView,
> ViewGroup.LayoutParams(context.screenWidth - 40, ViewGroup.LayoutParams.WRAP_CONTENT)
> )
> return this
> }
> 
> }

我在你的示例中做了小的调整，你可以试一下，看是否可以

```
class ScreenDialog(context: Context) : Dialog(context, R.style.CommentDialog) {

    private val binding:DialogScreenBinding by viewbind()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        initUI{

        }
    }


    fun initUI(action: (Int) -> Unit): ScreenDialog {

        window?.setGravity(Gravity.BOTTOM)
        
//        val contentView = layoutInflater.inflate(R.layout.dialog_screen, null, false);
//
//        contentView.iv_dialog_cancel.click {
//            dismiss()
//        }

        binding.rangeSeekBar.listenerPost = object :RangeSeekBar.OnRangeSeekBarPostListener {
            override fun onValuesChanged(minValue: Float, maxValue: Float) {
                Log.e("ScreenDialog",  "messageStr = $minValue $maxValue")
                ToastUtil.instance.show(context,messageStr = "$minValue $maxValue")
            }

            override fun onValuesChanged(min: Int, max: Int) {
                Log.e("ScreenDialog",  "messageStr = $min $max")
                ToastUtil.instance.show(context,messageStr = "$min $max")
            }
        }

        // range_slider.apply {
        // }

//        addContentView(
//            contentView,
//            ViewGroup.LayoutParams(context.screenWidth - 40, ViewGroup.LayoutParams.WRAP_CONTENT)
//        )

        return this
    }

}
```

**Comment by hi-dhl** [comment]
非常感谢你的提交，如果我的方案可以解决这个问题，我将要关闭这个 issue， 如果再次出现，欢迎你再次打开这个 issue， 或者重新提交
