### ISSUE TITLE
NoSuchMethodException问题

### ISSUE THREAD

**Issue by collinsmao** [hi-dhl/Binding#25]
问题: 在继承系统布局中，如果布局文件的根是merge标签，会抛出NoSuchMethodException；替换为ConstraintLayout等则不会。调试过，貌似原因是getMethod里调用的getPublicMethodRecursive只匹配了仅有LayoutInflater类型参数的infalte方法

merge标签产生的binding类也只有一个inflate(@NonNull LayoutInflater inflater,  @NonNull ViewGroup parent)这种签名的，作者有时间看看是不是这样？
备注：混淆添加了的

**Comment by hi-dhl** [comment]
不好意思，今天有点事，现在才回复
关于 merge 标签的处理，在项目 demo  里面有这个 case ，分为 ViewBinding 和 DataBinding, 在对应的地方，也有对应的注释， 界面有对应的 button，你可以运行一下，是否和你下现在案例相似

**Comment by collinsmao** [comment]
虽然情况不一样，还是谢谢了
