### ISSUE TITLE
使用viewbind时，如何在使用xml布局的自定义ViewGroup中使用呢

### ISSUE THREAD

**Issue by jqorz** [hi-dhl/Binding#26]
自定义ViewGroup布局名称`layout_empty_tip`，根标签使用了`<merge>`，
声明了`private val binding: LayoutEmptyTipBinding by viewbind()`
但是运行报错了

> java.lang.NoSuchMethodException: inflate [class android.view.LayoutInflater]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.hi.dhl.binding.ReflectExtKt.inflateMethod(ReflectExt.kt:17)
        at com.hi.dhl.binding.viewbind.ViewGroupViewBinding.<init>(ViewGroupViewBinding.kt:24)

看了下应该是反射没找到inflate方法
> fun <T> Class<T>.inflateMethod() = getMethod(INFLATE_NAME, LayoutInflater::class.java)

但是不知道怎么解决

**Comment by hi-dhl** [comment]
1. 检查一下有没有添加混淆
2. 我已经添加了，在 ViewGroup 中使用 `<merge>` ，示例如下所示

https://github.com/hi-dhl/Binding/blob/7adf8444187e72015014c586e971b75c37805627/app/src/main/java/com/hi/dhl/demo/binding/viewbind/ViewBindCustomView.kt#L36-L39

**Comment by jqorz** [comment]
> 1. 检查一下有没有添加混淆
> 2. 我已经添加了，在 ViewGroup 中使用 `<merge>` ，示例如下所示
> 
> https://github.com/hi-dhl/Binding/blob/7adf8444187e72015014c586e971b75c37805627/app/src/main/java/com/hi/dhl/demo/binding/viewbind/ViewBindCustomView.kt#L36-L39

你好，demo和我描述的情况不太一致，我的自定义View的根布局就是merge标签，这样我的merge的Binding没有可以绑定的对象

**Comment by hi-dhl** [comment]
已经修复，请升级到 1.1.3 的版本，即可

* 当根布局是非 merge 标签，使用此方法进行初始化 `val binding: LayoutViewCustomBinding by viewbind()` 
* 当根布局为 merge 标签，使用此方法进行初始化 `val binding: LayoutViewCustomBinding by viewbind(this)`

详细的 Demo 示例如下所示。

https://github.com/hi-dhl/Binding/blob/f3de58ddbe6eab07e6c32541b82f48d0c30239a2/app/src/main/java/com/hi/dhl/demo/binding/viewbind/ViewBindCustomView.kt#L26-L30

**Comment by jqorz** [comment]
> 已经修复，请升级到 1.1.3 的版本，即可
> 
> * 当根布局是非 merge 标签，使用此方法进行初始化 `val binding: LayoutViewCustomBinding by viewbind()`
> * 当根布局为 merge 标签，使用此方法进行初始化 `val binding: LayoutViewCustomBinding by viewbind(this)`
> 
> 详细的 Demo 示例如下所示。
> 
> https://github.com/hi-dhl/Binding/blob/f3de58ddbe6eab07e6c32541b82f48d0c30239a2/app/src/main/java/com/hi/dhl/demo/binding/viewbind/ViewBindCustomView.kt#L26-L30

感谢作者
