### ISSUE TITLE
版本时间写错啦，都2021年啦

### ISSUE THREAD

**Issue by Khaos116** [hi-dhl/Binding#27]
![image](https://user-images.githubusercontent.com/11989916/118434948-2008c880-b708-11eb-8375-429126e0f182.png)

**Comment by Khaos116** [comment]
另外，大佬，在BaseaActivity，BaseFragment，BaseDialog里面怎么用呢，有没有demo呀

**Comment by hi-dhl** [comment]
在 Activity 、Fragment 、Dialog 等等中的用法，项目里有案例，分为 databinding 和 viewbinding。

BaseaActivity，BaseFragment，BaseDialog 要根据你们项目的实际场景去封装了，举个例子：

如果要和之前的项目做兼容， 大部分项目 BaseaActivity 都会提供一个让子类重写布局 id 的方法， 类似于这种情况，需要自己单独封装一下， 返回 -1 就不进行布局的初始化，基于 Kotlin 的基础上，直接使用 binding 库就好了。

**Comment by Khaos116** [comment]
好的，我试试，3Q

**Comment by SomnusWu** [comment]
准备使用这个库，但是发现不知道Base如何使用了... 可以简单写个demo么

**Comment by hi-dhl** [comment]
> 准备使用这个库，但是发现不知道Base如何使用了... 可以简单写个demo么

@SomnusWu   这个要根据你的实际场景进行封装了，如果是老的项目，需要兼容旧的项目，我会在后面新出的项目中进行演示，如果在封装过程中遇到问题，可以加我WX，
