### ISSUE TITLE
自定义View的混淆规则

### ISSUE THREAD

**Issue by jqorz** [hi-dhl/Binding#29]
作者你好，之前向你反馈的自定义View使用viewbind导致的崩溃问题，升级1.1.3版本后，已经可以正常使用。但是混淆规则却没有跟着更新，这会导致自定义View的ViewBinding类中的inflate方法被混淆掉，导致异常。所以混淆规则需要新增一个```public static ** inflate(**,**);```，作者可以试一试

**Comment by hi-dhl** [comment]
感谢反馈，我立刻更新一下，忽略了 release 测试，我补上这块的测试用例

**Comment by jqorz** [comment]
或者改成```    public static ** bind(***);
    public static ** inflate(...);```
