### ISSUE TITLE
创建DataBinding时能否把xml里的对象传进去

### ISSUE THREAD

**Issue by br3ant** [hi-dhl/Binding#3]

**Comment by hi-dhl** [comment]
我举个例子，看是否和我理解的一致

```
    <data>

        <variable
            name="account"
            type="com.hi.dhl.demo.binding.Account" />

    </data>
```

初始化 DataBinding 的时候，同时给 account 赋值？  我的理解正确吗？

**Comment by br3ant** [comment]
是的，我加了一下，这样传个block进去，便于直接setVariable

inline fun <reified T : ViewDataBinding> Fragment.databind(noinline block: (ViewDataBinding.() -> Unit)? = null) = FragmentBindingDelegate<T>(this, block)

private val binding by databind<FragmentPlayListBinding> {
        setVariable(BR.m, playVM)
    }

**Comment by hi-dhl** [comment]
> 是的，我加了一下，这样传个block进去，便于直接setVariable
> 
> inline fun Fragment.databind(noinline block: (ViewDataBinding.() -> Unit)? = null) = FragmentBindingDelegate(this, block)
> 
> private val binding by databind {
> setVariable(BR.m, playVM)
> }

嗯嗯，如果我的理解是对的话，是可以加上的， 你的这样写法思路是对的，但是有点麻烦，我会在后续的版本加上这个

**Comment by hi-dhl** [comment]
但是有个问题咨询一下，你是在什么场景下会用到？

**Comment by br3ant** [comment]
正常场景下都会用到吧，如果不这样写的话，初始化和参数赋值就放在两个地方，而我更喜欢在一个地方把binding的配置弄好，这样在其他地方可以直接使用

**Comment by br3ant** [comment]
我错了，再不需要显示使用databinding的时候，懒加载这种写法会导致参数无法配置上去，而这种情况是比较多的，还是需要手动的去配置

**Comment by br3ant** [comment]
complete v1.0.4 close #3
