### ISSUE TITLE
关于ViewGroupDataBinding的一个问题

### ISSUE THREAD

**Issue by EdwinSmartBoy** [hi-dhl/Binding#33]
![image](https://user-images.githubusercontent.com/17477816/167360802-b71c2dc4-06f0-44e9-a655-69aeff2f32aa.png)
我看FragmentDataBinding等都有调用destroyed，但是ViewGroupDataBinding的没有看到调用，感觉会导致内存泄漏的样子。

**Comment by hi-dhl** [comment]
@EdwinSmartBoy  收到，非常感谢反馈，这个问题之前没想好处理方案，这两天我处理一下

**Comment by EdwinSmartBoy** [comment]
> @EdwinSmartBoy 收到，非常感谢反馈，这个问题之前没想好处理方案，这两天我处理一下

非常感谢，我看到好像只是viewbind修改了，databind还没有修改。
大佬啥时候能提个版本呀，哈哈

**Comment by hi-dhl** [comment]
嗯嗯，这两天会提个新版本

**Comment by EdwinSmartBoy** [comment]
> 嗯嗯，这两天会提个新版本

好的，非常感谢🥳🥳

**Comment by hi-dhl** [comment]
@EdwinSmartBoy  已经更新了， maven 也通过了，可以正常使用了 1.1.5

**Comment by EdwinSmartBoy** [comment]
> @EdwinSmartBoy 已经更新了， maven 也通过了，可以正常使用了 1.1.5

感谢！
