### ISSUE TITLE
在activity中绑定后没有使用binding，那么不生效

### ISSUE THREAD

**Issue by KunPengZheng** [hi-dhl/Binding#9]
在绑定后没有进行任何bindind的操作，那么不生效，因为代理只有在调用get方法的时候才会去调用getValue。

**Comment by hi-dhl** [comment]
嗯嗯，如果不进行任何操作是这样的，但是正常来说，如果用到了 binding ，那么最低应该会用到 view id， 例如 ` binding.textId.setText()` ,  如果都不进行 View 和 数据相关的任何操作的话，那么直接添加  ` tools:viewBindingIgnore="true"` 都不需要给 xml 生成对应的 binding 类了

**Comment by KunPengZheng** [comment]
哈哈，赞同作者的想法。但可能在一些demo场景下可能不会使用binding进行任意操作，作者可以在文档声明中说明这种情况。

**Comment by hi-dhl** [comment]
嗯嗯，后面在文档中补充一下， 其实 ViewBinding 官方文档也有这个说明

**Comment by hi-dhl** [comment]
非常感谢你的建议， 我已经在 README 中添加了说明，我将要关闭这个 issue，欢迎你再次提 issue
